### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by poiromaniax** [livehybrid/TA-aws-trusted-advisor#1]
Hi,

Thanks for releasing the TA-aws-trusted-advisor add-on!

Is there any documentation around it? Where does it need to be installed (On indexers? UFs? SearchHead?)

**Comment by livehybrid** [comment]
Apologies for the delay adding this. There is documentation now available at https://github.com/livehybrid/TA-aws-trusted-advisor/blob/main/README.md
