### ISSUE TITLE
Inputs and Configuration stuck "Loading"

### ISSUE THREAD

**Issue by poiromaniax** [livehybrid/TA-aws-trusted-advisor#2]
After installing the app, the Inputs and Configuration screens are just stuck "Loading"

**Comment by livehybrid** [comment]
Hi @poiromaniax - Please could you confirm which Splunk version you're using? I'll get onto this and also update the documentation.
Thanks

**Comment by poiromaniax** [comment]
8.1.0

I did also try follow the direct link you posted in someones thread on SplunkBase (dont recall the exact thread right now - but similar situation) and it told me something like "The URL does not exist or cannot be found"

**Comment by livehybrid** [comment]
Thanks. I've got an updated version and Documentation to upload tomorrow. I'll let you know once it is pushed.

**Comment by poiromaniax** [comment]
Thanks!

**Comment by livehybrid** [comment]
Sorry about the delay, Ive updated for version 1.0.7 (https://github.com/livehybrid/TA-aws-trusted-advisor/releases/download/v1.0.7/TA-aws-trusted-advisor-1.0.7-R98ba024.tar.gz)
I'll also get this updated on SplunkBase shortly.
There is documentation now available at https://github.com/livehybrid/TA-aws-trusted-advisor/blob/main/README.md
Please let me know if you have any issues with the new release. I've tested locally using docker (splunk/splunk:8.1).
Thanks
Will

**Comment by poiromaniax** [comment]
Thanks - I will install the update in the next day or two and let you know!

I appreciate the updates and documentation :)

**Comment by Chowdery** [comment]
Hi Will,
Unfortunately I seem to be encountering the same issue (even after downloading the latest version of the app). Basically the app opens ok (the dashboards show nothing as expected), but when clicking on the "Inputs" or "Configuration" tabs it just gets stuck with the "loading" icon spinning around.

We're running 8.0.4 which I think should be supported but we are also running this in Splunk Cloud (so not sure if that could be impacting the way the app works).

Any assistance would be appreciated :)

**Comment by livehybrid** [comment]
@Chowdery Apologies, I missed this. Please can you confirm which version you are running?
Thanks
Will
